name: build container -> niri-bootc
run-name: building container -> niri-bootc
on: 
  workflow_dispatch:
  push:
  schedule:
  - cron: '30 13 * * FRI'    # Triggers Fri at 13:30

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Run podman build
      run: sudo podman build -t niri-bootc --disable-compression=false .
    
    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | sudo podman login ghcr.io -u ${{ github.actor }} --password-stdin
    
    - name: Push image to ghcr.io
      run: sudo podman push niri-bootc ghcr.io/lanwrench/niri-bootc:latest