name: build container -> niri-bootc
run-name: building container -> niri-bootc
on: 
  workflow_dispatch:
  push:
  schedule:
  - cron: '30 13 * * FRI'    # Triggers Fri at 13:30

# env:
#   ARCH: x86_64
#   IMAGE_NAME: niri-bootc
#   IMAGE_REPO: ghcr.io/lanwrench
#   IMAGE_TAG: latest
#   IMAGE_SIGNED: false
#   VERSION: 42
#   VARIANT: container

jobs:
  io-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: run podman build
      run: podman build -t niri-bootc --disable-compression=false .
    - name: push image to ghcr.io
      run: podman push --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} niri-bootc ghcr.io/lanwrench/niri-bootc:latest

  build-iso:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
      # - name: Free disk space
      #   run: |
      #     sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/share/boost
      #     sudo df -h

      # - name: Install podman
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y podman

      - name: Build bootc container image
        run: |
          podman build -t localhost/niri-bootc:latest .

      - name: Generate bootable ISO
        run: |
          mkdir -p output
          
          sudo podman run --rm --privileged \
            --pull=newer \
            --security-opt label=type:unconfined_t \
            -v /var/lib/containers/storage:/var/lib/containers/storage \
            -v $(pwd)/output:/output \
            quay.io/centos-bootc/bootc-image-builder:latest \
            localhost/niri-bootc:latest \
            --type iso \
            --local

      - name: List output
        run: |
          find output -type f
          ls -lh output/

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: bootable-iso
          path: output/**/*.iso
