name: build container -> niri-bootc
run-name: building container -> niri-bootc
on: 
  workflow_dispatch:
  push:
  schedule:
  - cron: '30 13 * * FRI'    # Triggers Fri at 13:30

env:
  ARCH: x86_64
  IMAGE_NAME: bootc-niri
  IMAGE_REPO: ghcr.io/lanwrench
  IMAGE_TAG: latest
  VERSION: 1.0
  VARIANT: 42

jobs:
  io-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: run podman build
      run: podman build -t niri-bootc --disable-compression=false .
    - name: push image to ghcr.io
      run: podman push --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} niri-bootc ghcr.io/lanwrench/niri-bootc:latest

    - name: Build ISO
      uses: jasonn3/build-container-installer@main
      id: build
      with:
        arch: ${{ env.ARCH}}
        image_name: ${{ env.IMAGE_NAME}}
        image_repo: ${{ env.IMAGE_REPO}}
        image_tag: ${{ env.IMAGE_TAG }}
        version: ${{ env.VERSION }}
        variant: ${{ env.VARIANT }}
        iso_name: ${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG }}-${{ env.VERSION }}.iso

    # This example is for uploading your ISO as a Github artifact. You can do something similar using any cloud storage, so long as you copy the output
    - name: Upload ISO as artifact
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.build.outputs.iso_name }}
        path: |
          ${{ steps.build.outputs.iso_path }}/${{ steps.build.outputs.iso_name }}
          ${{ steps.build.outputs.iso_path }}/${{ steps.build.outputs.iso_name }}-CHECKSUM
        if-no-files-found: error
        retention-days: 0
        compression-level: 0
