name: build container -> niri-bootc
run-name: building container -> niri-bootc
on: 
  workflow_dispatch:
  push:
  schedule:
  - cron: '30 13 * * FRI'    # Triggers Fri at 13:30


jobs:
  io-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: run podman build
      run: podman build -t niri-bootc --disable-compression=false .
    - name: push image to ghcr.io
      run: podman push --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} niri-bootc ghcr.io/LANWrench/niri-bootc:latest
